spring:
  datasource:

    sales:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/infratec
      username: infratec
      password: infratec@4754
      hikari:
        data-source-properties:
          lc_ctype: UTF8
          format_sql: true
          show-sql: true


logging:

  level:
    org.springframework.web: DEBUG
    org.springframework.ws.client.MessageTracing: TRACE
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.server.MessageTracing.sent: TRACE
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.HttpLogging: TRACE
    org.hibernate.SQL: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
